# Numpy

In [4]:
import numpy as np

In [5]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
myarr = np.array(mylist)

In [8]:
myarr

array([1, 2, 3])

In [9]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(1)

array([0.47215627])

In [20]:
np.random.rand(5,2)

array([[0.67907508, 0.60522834],
       [0.53657446, 0.43395466],
       [0.28727172, 0.90674414],
       [0.87259663, 0.64544407],
       [0.64670259, 0.27084631]])

In [21]:
np.random.randn(10)

array([-0.51941037,  0.56843959,  0.06897994,  1.06416142, -0.93954792,
       -0.29791695,  0.46383712,  1.41418286,  0.0372967 ,  0.12565124])

In [22]:
np.random.randn(2,3)

array([[-0.31125009,  0.61465942,  1.33271835],
       [-0.96264067, -0.64273206, -0.50484946]])

In [23]:
np.random.randint(0,101,5)

array([91, 75, 81, 73, 55])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
arr = np.arange(0,25) + 1

In [29]:
arr.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
ranarr = np.random.randint(0,101,10)

In [31]:
ranarr.max()

99

In [32]:
ranarr.min()

2

In [33]:
ranarr.argmax()

5

In [34]:
ranarr.argmin()

7

In [35]:
ranarr.dtype

dtype('int64')

In [36]:
arr = np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[8]

8

In [39]:
arr[1:5]

array([1, 2, 3, 4])

In [40]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [41]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr_copy = arr.copy()

In [43]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [47]:
arr_2d.sum()

225

In [48]:
arr_2d.sum(axis=0)

array([60, 75, 90])

In [49]:
arr_2d.sum(axis=1)

array([ 30,  75, 120])